// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package view

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC47a0c8eDecodeGithubComRuslanDantsovGophermartInternalDtoView(in *jlexer.Lexer, out *AuthUserViewModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "access_token":
			out.AccessToken = string(in.String())
		case "expires_in":
			out.ExpiresIn = int(in.Int())
		case "token_type":
			out.TokenType = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC47a0c8eEncodeGithubComRuslanDantsovGophermartInternalDtoView(out *jwriter.Writer, in AuthUserViewModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"expires_in\":"
		out.RawString(prefix)
		out.Int(int(in.ExpiresIn))
	}
	{
		const prefix string = ",\"token_type\":"
		out.RawString(prefix)
		out.String(string(in.TokenType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuthUserViewModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC47a0c8eEncodeGithubComRuslanDantsovGophermartInternalDtoView(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuthUserViewModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC47a0c8eEncodeGithubComRuslanDantsovGophermartInternalDtoView(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuthUserViewModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC47a0c8eDecodeGithubComRuslanDantsovGophermartInternalDtoView(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuthUserViewModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC47a0c8eDecodeGithubComRuslanDantsovGophermartInternalDtoView(l, v)
}
