// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package view

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD4bf1ad6DecodeGithubComRuslanDantsovGophermartInternalDtoView(in *jlexer.Lexer, out *BalanceViewModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "current":
			out.Current = float64(in.Float64())
		case "withdrawn":
			out.Withdrawn = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD4bf1ad6EncodeGithubComRuslanDantsovGophermartInternalDtoView(out *jwriter.Writer, in BalanceViewModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"current\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Current))
	}
	{
		const prefix string = ",\"withdrawn\":"
		out.RawString(prefix)
		out.Float64(float64(in.Withdrawn))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BalanceViewModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD4bf1ad6EncodeGithubComRuslanDantsovGophermartInternalDtoView(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BalanceViewModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD4bf1ad6EncodeGithubComRuslanDantsovGophermartInternalDtoView(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BalanceViewModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD4bf1ad6DecodeGithubComRuslanDantsovGophermartInternalDtoView(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BalanceViewModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD4bf1ad6DecodeGithubComRuslanDantsovGophermartInternalDtoView(l, v)
}
