// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package view

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC68243e7DecodeGithubComRuslanDantsovGophermartInternalDtoView(in *jlexer.Lexer, out *UserViewModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "login":
			out.Login = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC68243e7EncodeGithubComRuslanDantsovGophermartInternalDtoView(out *jwriter.Writer, in UserViewModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix)
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserViewModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC68243e7EncodeGithubComRuslanDantsovGophermartInternalDtoView(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserViewModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC68243e7EncodeGithubComRuslanDantsovGophermartInternalDtoView(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserViewModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC68243e7DecodeGithubComRuslanDantsovGophermartInternalDtoView(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserViewModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC68243e7DecodeGithubComRuslanDantsovGophermartInternalDtoView(l, v)
}
