// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package view

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5ec55c3eDecodeGithubComRuslanDantsovGophermartInternalDtoView(in *jlexer.Lexer, out *WithdrawViewModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.OrderNumber = string(in.String())
		case "sum":
			out.Sum = float64(in.Float64())
		case "processed_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ProcessedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5ec55c3eEncodeGithubComRuslanDantsovGophermartInternalDtoView(out *jwriter.Writer, in WithdrawViewModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.OrderNumber))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Sum))
	}
	{
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		out.Raw((in.ProcessedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawViewModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5ec55c3eEncodeGithubComRuslanDantsovGophermartInternalDtoView(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawViewModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5ec55c3eEncodeGithubComRuslanDantsovGophermartInternalDtoView(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawViewModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5ec55c3eDecodeGithubComRuslanDantsovGophermartInternalDtoView(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawViewModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5ec55c3eDecodeGithubComRuslanDantsovGophermartInternalDtoView(l, v)
}
